services:
  db:
    build:
      context: ./db
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_database
      - mysql_user
      - mysql_password

  api:
    build:
      context: ./api
    container_name: flask-api
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      API_PORT: 8000
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE_FILE: /run/secrets/mysql_database
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_database
      - mysql_user
      - mysql_password

  frontend:
    build:
      context: ./app
    container_name: nextjs
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      API_URL: http://api:8000

secrets:
  mysql_root_password:
    file: ./secrets/db_root_password
  mysql_database:
    file: ./secrets/db_name
  mysql_user:
    file: ./secrets/db_user
  mysql_password:
    file: ./secrets/db_password