name: CD Pipeline App
run-name: "Triggered by @${{ github.actor }} on ${{ github.repository }} [${{ github.ref_name }}] - ${{ github.event_name }}"

on:
  push:
    branches:
      - 'main'
    paths:
      - 'app/**'

jobs:
  deploy:
    name: Force Deploy ECS Service
    runs-on: ubuntu-latest

    steps:
    - name: Get the repo
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Force new deployment
      run: |
        aws ecs update-service \
          --cluster ${{ secrets.AWS_ECS_CLUSTER_NAME }} \
          --service nextjs-service \
          --force-new-deployment