name: CI Pipeline
run-name: Triggered by @${{ github.actor }}

on:
    pull_request:
      branches:
        - 'main'
  
jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
          - name: Get the repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Run the gitleaks
            uses: gitleaks/gitleaks-action@v2