name: CI Pipeline
run-name: Triggered by @${{ github.actor }}

on:
    pull_request:
      branches:
        - 'main'
  
jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
          - name: Get the repo
            uses: actions/checkout@v4
            with:
              fetch-depth: 0
    
          - name: Run the gitleaks
            uses: gitleaks/gitleaks-action@v2

    sonarcloud:
        runs-on: ubuntu-latest
        needs: [gitleaks]
        steps:
          - name: Get the repo
            uses: actions/checkout@v4
            with:
                fetch-depth: 0
    
          - name: SonarCloud Scan
            uses: sonarsource/sonarcloud-github-action@v3.1.0
            env:
                SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}